version: "3.8"

volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env.example
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5

  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
