// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/dao.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	daolib "github.com/WantBeASleep/goooool/daolib"
	gomock "github.com/golang/mock/gomock"
)

// MockDAO is a mock of DAO interface.
type MockDAO struct {
	ctrl     *gomock.Controller
	recorder *MockDAOMockRecorder
}

// MockDAOMockRecorder is the mock recorder for MockDAO.
type MockDAOMockRecorder struct {
	mock *MockDAO
}

// NewMockDAO creates a new mock instance.
func NewMockDAO(ctrl *gomock.Controller) *MockDAO {
	mock := &MockDAO{ctrl: ctrl}
	mock.recorder = &MockDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDAO) EXPECT() *MockDAOMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDAO) BeginTx(ctx context.Context, opts ...daolib.TxOption) (context.Context, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginTx", varargs...)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDAOMockRecorder) BeginTx(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDAO)(nil).BeginTx), varargs...)
}

// CommitTx mocks base method.
func (m *MockDAO) CommitTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockDAOMockRecorder) CommitTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockDAO)(nil).CommitTx), ctx)
}

// NewInfoQuery mocks base method.
func (m *MockDAO) NewInfoQuery(ctx context.Context) InfoQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewInfoQuery", ctx)
	ret0, _ := ret[0].(InfoQuery)
	return ret0
}

// NewInfoQuery indicates an expected call of NewInfoQuery.
func (mr *MockDAOMockRecorder) NewInfoQuery(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInfoQuery", reflect.TypeOf((*MockDAO)(nil).NewInfoQuery), ctx)
}

// NewInvQuery mocks base method.
func (m *MockDAO) NewInvQuery(ctx context.Context) InvQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewInvQuery", ctx)
	ret0, _ := ret[0].(InvQuery)
	return ret0
}

// NewInvQuery indicates an expected call of NewInvQuery.
func (mr *MockDAOMockRecorder) NewInvQuery(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInvQuery", reflect.TypeOf((*MockDAO)(nil).NewInvQuery), ctx)
}

// NewRepo mocks base method.
func (m *MockDAO) NewRepo(ctx context.Context, querier daolib.BaseQuerySetter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewRepo", ctx, querier)
}

// NewRepo indicates an expected call of NewRepo.
func (mr *MockDAOMockRecorder) NewRepo(ctx, querier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRepo", reflect.TypeOf((*MockDAO)(nil).NewRepo), ctx, querier)
}

// NewTransQuery mocks base method.
func (m *MockDAO) NewTransQuery(ctx context.Context) TransQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTransQuery", ctx)
	ret0, _ := ret[0].(TransQuery)
	return ret0
}

// NewTransQuery indicates an expected call of NewTransQuery.
func (mr *MockDAOMockRecorder) NewTransQuery(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTransQuery", reflect.TypeOf((*MockDAO)(nil).NewTransQuery), ctx)
}

// NewUserQuery mocks base method.
func (m *MockDAO) NewUserQuery(ctx context.Context) UserQuery {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserQuery", ctx)
	ret0, _ := ret[0].(UserQuery)
	return ret0
}

// NewUserQuery indicates an expected call of NewUserQuery.
func (mr *MockDAOMockRecorder) NewUserQuery(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserQuery", reflect.TypeOf((*MockDAO)(nil).NewUserQuery), ctx)
}

// RollbackTx mocks base method.
func (m *MockDAO) RollbackTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockDAOMockRecorder) RollbackTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockDAO)(nil).RollbackTx), ctx)
}
